= Less plugin

== Juzu Less Plugin

LESS is a dynamic stylesheet language which extends CSS with dynamic behavior such as variables, mixins, operations
and functions. LESS is easy to learn thanks to the http://lesscss.org/[online documentation].

Juzu provides a LESS plugin that takes care of compiling a LESS stylesheet into a CSS stylesheet which
are then served by the Asset plugin. This chapter explains how to use LESS and combine it with the <<assets>> plugin.

== Usage ==

The LESS plugin operates at compilation time only because the only task he has to do is to transform a LESS
source code into a CSS stylesheet. The runtime part is usually done by the Asset plugin.

The +@Less+ annotation annotates a package containing an +assets+ package. This +assets+ package should contain
 the LESS files to be compiled.

.Annotating an application package for processing LESS files
[source,java]
----
@Less("stylesheet.less")
@Application
package myapp;

import juzu.plugin.less.Less;
----

The _stylesheet.less_ file will be located in the +myapp.assets+ package. The +assets+ child package of the
annotated package should contain the stylesheet, this is done on purpose to coincide exactly with the
+assets+ package used by the Asset plugin. During the compilation phase the _stylesheet.less_ will be compiled
to the _stylesheet.css_. If we want this file to be served with the application we simply add the corresponding
+@Stylesheets+ annotation:

.LESS and Asset plugins in action
[source,java]
----
@Less("stylesheet.less")
@Stylesheets({
  @Stylesheet(value = "stylesheet.css", location = AssetLocation.CLASSPATH)
})
@Application
package myapp;

import juzu.Application;
import juzu.asset.AssetLocation;
import juzu.plugin.less.Less;
import juzu.plugin.asset.Assets;
import juzu.plugin.asset.Stylesheet;
----

By default LESS will use a default formatting for the generated CSS. To achieve smaller CSS size, a _minify_ option
can be used, this option will trim the whitespace when processing the file : +@Less(value = "stylesheet.less", minify = true)+.

=== Building

Add the Less plugin jar to your compilation classpath.

In Maven it can achieved by adding the Less plugin dependency to your POM:

[source,xml,subs="attributes,specialcharacters"]
----
<dependency>
  <groupId>org.juzu</groupId>
  <artifactId>juzu-plugins-less</artifactId>
  <version>{juzu-version}</version>
</dependency>
----
