[[servlet]]
= Servlet plugin

The servlet plugin enhance Juzu servlet applications.

== Servlet declaration

A Juzu servlet application is managed by a ##JuzuServlet## configured with the application name. Since Servlet 3.0,
configuration can be easier thanks to servlet annotations. Juzu leverages this capability and is able to generate a
servlet for an application with the ##juzu.plugin.servlet.Servlet## annotation:

.Juzu servlet generation
[source,java]
----
@Application
@Servlet("/") // <1>
package my.application;
----
<1> The application _url-pattern_

[[servlet_bundle]]
== Resource bundle declaration

The +@Servlet+ annotation allows to declare a resource bundle:

.Servlet resource bundle configuration via annotations
[source,java]
----
@Application
@Servlet(value = "/", resourceBundle = "MyBundle")
package myapp;
----

== Asset server automatic registration

The jar of the servlet plugin contains a _web-fragment.xml_ that automatically declares the asset servlet simplifying
further more the configuration of the application.
