== Juzu WebJars Plugin

http://www.webjars.org/[WebJars] are client-side web libraries (e.g. jQuery & Bootstrap) packaged into jar files.
WebJars allow to declaratively set the version, use a consistent version across an application, and easily deal with transitive dependencies.

Juzu provides a WebJars plugin that copies resources in jar libraries to application assets and then served by the _Asset_
plugin or the _AMD_ plugin.


=== Usage

.Annotating an application package for declaring WebJars
[source,java]
----
@Application
@WebJars("foo.js")
package myapp;

import juzu.Application;
import juzu.plugin.webjars.WebJars;
----

[source,xml]
----
<dependency>
  <groupId>org.webjars</groupId>
  <artifactId>foo</artifactId>
  <version>1.0</version>
</dependency>
----

The _foo.js_ file will be located in the +myapp.assets+ package.

If we want this file to be served with the application we simply add the corresponding +@Assets+ annotation:

.WebJars and Asset plugin in action
[source,java]
----
@Application
@WebJars("foo.js")
@Assets(scripts = { 
  @Script(
    id = "foo", 
    src="foo.js"
  ) 
})
package myapp;

import juzu.Application;
import juzu.plugin.asset.Assets;
import juzu.plugin.asset.Script;
import juzu.plugin.webjars.WebJars;
----

It can also be used as a JavaScript module with the _AMD_ plugin:

.WebJars and AMD plugin in action
[source,java]
----
@Application
@WebJars("foo.js")
@Defines({
  @Define(
    name = "Foo", 
    path="foo.js"
  ),
  @Define(
    name = "Bar", 
    path="bar.js",
    dependencies = {@Dependency(name = "Foo")}
  )
})  
package myapp;

import juzu.Application;
import juzu.plugin.amd.Define;
import juzu.plugin.amd.Defines;
import juzu.plugin.amd.Dependency;
import juzu.plugin.webjars.WebJars;
----


=== Building

Add the WebJars plugin jar to your compilation classpath.

In Maven it can achieved by adding the WebJars plugin dependency to your POM:

[source,xl]
----
<dependency>
  <groupId>org.juzu</groupId>
  <artifactId>juzu-plugins-webjars</artifactId>
  <version>$[juzu.version]</version>
</dependency>
----
