:docinfo1: docinfo1

= Step 5 - Save Secrets

= eXo services and eXo JCR storage
We are now a *JuZcret application* with some *nice features*. However we're saving our secret in memory... which is good for testing but not for production. It's time to learn how to *save our secret* in *eXo JCR*. During this step we will implement a new secret service for save all secrets in JCR instead of memory.

== Binding eXo JCR service
We'll not focus on eXo JCR api on this tutorial, but how to *leverage JCR support from PLF*. First, we need to declare dependency on eXo kernel in the classpath. Add this to the project +pom.xml+:

[source,xml]
----
   <dependency>
      <groupId>org.exoplatform.jcr</groupId>
      <artifactId>exo.jcr.component.ext</artifactId>
      <version>1.15.x-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
----

It's ready for us to implement the *new secret service* with *JCR api*. Let's create a new *SecretServiceJCRImpl* class in the +org.juzu.tutorial.services+ package:

[source,java]
----

import org.exoplatform.services.jcr.ext.app.SessionProviderService;
import org.exoplatform.services.jcr.ext.hierarchy.NodeHierarchyCreator;

public class SecretServiceJCRImpl implements SecretService {
  @Inject
    private SessionProviderService  sessionService;

    @Inject
private NodeHierarchyCreator    nodeCreator;
  ...
}
----

*sessionService* and *nodeCreator* are service components that was created by eXo container. There must be a bridge between PLF's container (eXo container) and JuZcret's IOC container (Guice). This means that before to use it we need to @Bind the necessary services in +package-info.java+:

[source,java]
----
@Bindings({ @Binding(value = SecretService.class, implementation = SecretServiceJCRImpl.class),
          @Binding(value = SessionProviderService.class), @Binding(value = NodeHierarchyCreator.class)})
----

The *secret service implementation* is now JCR version. Notice that there is *no declaration* for implementation class of +SessionProviderService+ and +NodeHierarchyCreator+. We only declare the interfaces here because *JuZcret's IOC container* will not instantiate those services itself, but retrieve them from *PLF's container* by delegating the call to +KernelProviderFactory+ (we declared this in step-4 using service loader).

== JCR service implementation

All the necessary services are now managed by *JuZcret's container*, and ready to be injected and used, the +NodeHierarchyCreator+ service will help us to init our JuZcret application *JCR data structure*. We create the root node of JuZcret application by adding this method to our secret service:

[source,java]
----
public class SecretServiceJCRImpl implements SecretService {
  ...
  private Node getSecretHome() throws Exception {
    SessionProvider sProvider = sessionService.getSystemSessionProvider(null);
    Node publicApp = nodeCreator.getPublicApplicationNode(sProvider);
    try {
      return publicApp.getNode(SECRET_APP);
    } catch (Exception e) {
      Node secretApp = publicApp.addNode(SECRET_APP, "nt:unstructured");
      publicApp.getSession().save();
      return secretApp;
    }
    ...
  }
}
----

By calling +nodeCreator#getPublicApplicationNode+ method, we get the common place to put *application data*. If it's the first time running JuZcret, we create a new +SECRET_APP+ node with type +nt:unstructured+ node type. This node will then contains childrens with node type +exo:secret+. This node type should reflect our Secret domain class, and then declare this to *eXo JCR service* (we'll back to this next part)

Now we have the root application node, lets implement the function to *add a new  secret*:

[source,java]
----
public class SecretServiceJCRImpl implements SecretService {
  …

  public void addSecret(String message, String imageUrl) {
    String id = UUID.randomUUID().toString();
    try {
      Node secretHome = getSecretHome();
      Node secret = secretHome.addNode(id, SECRET_NODE_TYPE);
      secret.setProperty(ID, id);
      secret.setProperty(MESSAGE, message);
      secret.setProperty(IMAGE_URL, imageUrl);
      secret.setProperty(CREATED_DATE, Calendar.getInstance());
      secret.getSession().save();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
  ...
}
----

It's pretty simple *JCR api*, and actually, no Juzu stuff here, the most important thing here is getting the root node using the +getSecretHome+ method:

[source,java]
----
private Node getSecretHome() throws Exception {
    SessionProvider sProvider = sessionService.getSystemSessionProvider(null);
    Node publicApp = nodeCreator.getPublicApplicationNode(sProvider);
    try {
      return publicApp.getNode(SECRET_APP);
    } catch (Exception e) {
      Node secretApp = publicApp.addNode(SECRET_APP, "nt:unstructured");
      publicApp.getSession().save();
      return secretApp;
    }
  }
----

There are some other *similar method* that we need to implement: +addComment+, +addLike+ and +getSecrets+ method:

[source,java]
----
@Override
  public List<Secret> getSecrets() {
    List<Secret> secrets = new LinkedList<Secret>();
    try {
      Node secretHome = getSecretHome();
      NodeIterator iterChild = secretHome.getNodes();
      while (iterChild.hasNext()) {
        secrets.add(buildSecret(iterChild.nextNode()));
      }
      return secrets;
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  @Override
  public Comment addComment(String secretId, Comment comment) {
    String id = UUID.randomUUID().toString();

    try {
      Node secret = getSecretNode(secretId);

      if (secret != null) {
        Node cNode = secret.addNode(id, COMMENT_NODE_TYPE);
        cNode.setProperty(ID, id);
        cNode.setProperty(USER_ID, comment.getUserId());
        cNode.setProperty(CONTENT, comment.getContent());
        cNode.setProperty(CREATED_DATE, Calendar.getInstance());

        cNode.getSession().save();
        return buildComment(cNode);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }

  @Override
  public Set<String> addLike(String secretId, String userId) {
    try {
      Node secret = getSecretNode(secretId);

      if (secret != null) {
        Set<String> likes = new HashSet<String>();
        if (secret.hasProperty(LIKES)) {
          Value[] values = secret.getProperty(LIKES).getValues();
          for (Value v : values) {
            likes.add(v.getString());
          }
        }
        likes.add(userId);
        secret.setProperty(LIKES, likes.toArray(new String[likes.size()]));

        secret.save();
        return likes;
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
 }

  private Node getSecretNode(String secretId) {
    try {
      Node secretHome = getSecretHome();
      Node secret = secretHome.getNode(secretId);
      return secret;
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

private Secret buildSecret(Node secretNode) throws RepositoryException {
    Secret secret = new Secret();

    List<Comment> comments = new LinkedList<Comment>();
    NodeIterator commentIter = secretNode.getNodes();
    while (commentIter.hasNext()) {
      comments.add(buildComment(commentIter.nextNode()));
    }
    secret.setComments(comments);

    secret.setCreatedDate(secretNode.getProperty(CREATED_DATE).getDate().getTime());
    secret.setId(secretNode.getProperty(ID).getString());
    secret.setImageURL(secretNode.getProperty(IMAGE_URL).getString());

    Set<String> likes = new HashSet<String>();
    if (secretNode.hasProperty(LIKES)) {
      for (Value userID : secretNode.getProperty(LIKES).getValues()) {
        likes.add(userID.getString());
      }
    }
    secret.setLikes(likes);

    secret.setMessage(secretNode.getProperty(MESSAGE).getString());
    return secret;
  }

  private Comment buildComment(Node commentNode) throws RepositoryException {
    Comment comment = new Comment();
    comment.setContent(commentNode.getProperty(CONTENT).getString());
    comment.setCreatedDate(commentNode.getProperty(CREATED_DATE).getDate().getTime());
    comment.setId(commentNode.getProperty(ID).getString());
    comment.setUserId(commentNode.getProperty(USER_ID).getString());
    return comment;
  }

----

The secret JCR service should be now ready to use. We just need before to make eXo JCR to be aware about secret's *JCR node type*. Lets configure *eXo JCR service*.

== JuzCret JCR NodeType declaration

Create *JCR node type definition* file +secret-nodetypes.xml+ in +src/main/webapp/WEB-INF/conf+ . We'll define +exo:secret+ and +exo:secretComment+ node type. Their properties reflect our *JuZcret domain classes*: Secret and Comment. We'll not explain the JCR node type definition here, if you need more information to understand the code below, please take a look to the eXo JCR website.

[source,xml]
----
<nodeTypes xmlns:nt="http:+www.jcp.org/jcr/nt/1.0" xmlns:mix="http:+www.jcp.org/jcr/mix/1.0" xmlns:jcr="http:+www.jcp.org/jcr/1.0">
    <nodeType name="exo:secret" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
      <supertypes>
        <supertype>nt:base</supertype>
      </supertypes>
      <propertyDefinitions>
        <propertyDefinition name="exo:id" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:message" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:imageURL" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:likes" requiredType="String" autoCreated="false" mandatory="false" onParentVersion="COPY" protected="false" multiple="true">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:createdDate" requiredType="Date" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
      </propertyDefinitions>
      <childNodeDefinitions>
        <childNodeDefinition name="*" defaultPrimaryType="" autoCreated="false" mandatory="false"
          onParentVersion="COPY" protected="false" sameNameSiblings="false">
          <requiredPrimaryTypes>
            <requiredPrimaryType>exo:secretComment</requiredPrimaryType>
          </requiredPrimaryTypes>
        </childNodeDefinition>
      </childNodeDefinitions>
    </nodeType>

    <nodeType  name="exo:secretComment" isMixin="false" hasOrderableChildNodes="false" primaryItemName="">
      <supertypes>
        <supertype>nt:base</supertype>
      </supertypes>
      <propertyDefinitions>
        <propertyDefinition name="exo:id" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:userId" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:content" requiredType="String" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
        <propertyDefinition name="exo:createdDate" requiredType="Date" autoCreated="false" mandatory="true" onParentVersion="COPY" protected="false" multiple="false">
          <valueConstraints/>
        </propertyDefinition>
      </propertyDefinitions>
    </nodeType>
</nodeTypes>
----

After have +secret-nodetypes.xml+ file ready, lets register it to *eXo JCR service*. Add this new eXo container configuration file +/src/main/webapp/WEB-INF/conf/configuration.xml+:

[source,xml]
----
<configuration
  xmlns:xsi="http:+www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd"
  xmlns="http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd">

  <external-component-plugins>
    <target-component>org.exoplatform.services.jcr.RepositoryService</target-component>
    <component-plugin>
      <name>add.nodeType</name>
      <set-method>addPlugin</set-method>
      <type>org.exoplatform.services.jcr.impl.AddNodeTypePlugin</type>
      <init-params>
        <values-param>
          <name>autoCreatedInNewRepository</name>
          <description>Node types configuration file</description>
          <value>war:/conf/secret-nodetypes.xml</value>
        </values-param>
      </init-params>
    </component-plugin>
  </external-component-plugins>
</configuration>
----

This configuration register a *node type plugin* with eXo RepositoryService, which will parse our node type at +war:/conf/secret-nodetypes.xml+ path.

The only missing thing now is that make sure PLF will *scan and process* our *configuration.xml* file in *tutorial-juzcret webapp* when it initializing eXo container. This task is not specific to Juzu, it's about configuring a webapp as *PLF extension* (for more details about PLF extension, pls look at eXo kernel document)

First, we need to modify the +web.xml+:

[source,xml]
----
<?xml version="1.0" encoding="ISO-8859-1" ?>
<web-app xmlns="http:+java.sun.com/xml/ns/javaee"
         xmlns:xsi="http:+www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http:+java.sun.com/xml/ns/javaee http:+java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0">
  <display-name>tutorial-juzcret</display-name>

  <!-- Run mode: prod, dev or live -->
  <context-param>
    <param-name>juzu.run_mode</param-name>
    <param-value>${juzu.run_mode:dev}</param-value>
  </context-param>

  <!-- Injection container to use: guice, spring, cdi or weld -->
  <context-param>
    <param-name>juzu.inject</param-name>
    <param-value>guice</param-value>
  </context-param>

  <listener>
    <listener-class>org.exoplatform.container.web.PortalContainerConfigOwner</listener-class>
  </listener>
</web-app>
----

*eXo container* will need to know which webapp container contains its configuration files. By adding the +PortalContainerConfigOwner+ a *servlet context listener*, we've registered JuZcret webapp context to eXo container to scan and process xml configuration file. Notice that we also need to declare +<display-name>+ tag. eXo container use that information to *map the registered webapp*.

At last, we config the JuZcret as a *dependency of eXo container*. Even you've registered the webapp context, we still need to tell eXo container that JuZcret webapp is a *portal container definition dependency*. There are 2 places to add the configuration:

* +TOMCAT/gatein/conf/configuration.xml+
* Create a jar file, contains +/conf/configuration.xml+ and put it into tomcat/lib

We take 1st solution for this tutorial, it's simple and easy to do. Lets modify that configuration file:

[source,xml]
----
<configuration
    xmlns:xsi="http:+www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd"
    xmlns="http:+www.exoplatform.org/xml/ns/kernel_1_2.xsd">

<external-component-plugins>
<target-component>org.exoplatform.container.definition.PortalContainerConfig</target-component>
  <component-plugin>
  <!-- The name of the plugin -->
  <name>Change PortalContainer Definitions</name>
  <!-- The name of the method to call on the PortalContainerConfig in order to register the changes on the PortalContainerDefinitions -->
  <set-method>registerChangePlugin</set-method>
  <!-- The full qualified name of the PortalContainerDefinitionChangePlugin -->
  <type>org.exoplatform.container.definition.PortalContainerDefinitionChangePlugin</type>
  <init-params>
    <value-param>
      <name>apply.default</name>
      <value>true</value>
    </value-param>
    <object-param>
      <name>change</name>
      <object type="org.exoplatform.container.definition.PortalContainerDefinitionChange$AddDependencies">
        <!-- The list of name of the dependencies to add -->
        <field name="dependencies">
          <collection type="java.util.ArrayList">
            <value>
              <string>tutorial-juzcret</string>
            </value>
          </collection>
        </field>
      </object>
    </object-param>
  </init-params>
    </component-plugin>
</external-component-plugins>

<import>jar:/conf/platform/configuration.xml</import>

</configuration>
----

Notice that it's important to declare it before the import of +jar:/conf/platform/configuration.xml+.

We add the *JuZcret webapp context as a portal container definition dependency*.
That's all, now re-compile and deploy JuZcret app to PLF tomcat.
All features: sharing secret, adding comment, like... should run similar to previous memory service implementation, except one thing, we *don't lose shared secret* or comment after restarting server. The data is now *really persisted !*

Let's continue by link:./step6.html[adding internationalization in the next step]

_The final source of step 5 is available for link:https://github.com/juzu/portlet-tutorial/tree/step-5[downloading on Github]_
