:docinfo1: docinfo1

= Juzu Reference Guide
Julien Viet <http://www.julienviet.com>

Juzu is a web framework based on MVC concepts for developing applications. Juzu is an
open source project developed on https://github.com/juzu/juzu[GitHub] licensed under the
http://www.apache.org/licenses/LICENSE-2.0[Apache 2 License].

This tutorial will make you familliar with Juzu, to reach your objective you will develop a weather application
in several steps, each step introducing a new feature to gradually build the application.

[[quickstart]]
= Quickstart

include::weather1.asciidoc[]

[[template_overview]]
= Template overwiew

include::weather2.asciidoc[]

[[dependency_injection]]
= Dependency Injection

include::weather3.asciidoc[]

[[views]]
= Views

include::weather4.asciidoc[]

[[actions]]
= Actions

include::weather5.asciidoc[]

[[type_safe_templating]]
= Type safe templating

include::weather6.asciidoc[]

[[styled]]
= Styling the application

include::weather7.asciidoc[]

[[ajax]]
= Adding Ajax

include::weather8.asciidoc[]

[[testing]]
= Testing our application

include::testing.asciidoc[]

= Wrap up

We reached the ends our walk through Juzu, now you can learn more and study the Booking application. This application
can be found in the package you downloaded in the _booking_ directory.
